version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=19981024
      - POSTGRES_DB=simple_bank
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:19981024@postgres:5432/simple_bank?sslmode=disable
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/startup.sh"]
    command: ["/app/main"]

