apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - userarn: arn:aws:iam::269018787119:user/github-ci
      username: github-ci
      groups:
        - system:masters