name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:12
        # Provide the password for postgres
        env:
          POSTGRES_DB: simple_bank
          POSTGRES_USER: ${{ secrets.POSTGRESDB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRESDB_PASSWORD }}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: check out code into Go module directory
      uses: actions/checkout@v3

    - name: migrate db to postgres
      run: make migrateup

    - name: Run all unit tests
      run: make test